SELECT * FROM transjakarta;
-- ANALISIS JUMLAH TOTAL PERJALANAN
SELECT COUNT(*) 
FROM transjakarta;
-- ANALISIS PEMBAYARAN
-- A. TOTAL PEMBAYARAN
SELECT SUM(PAYAMOUNT) 
FROM transjakarta;
-- B. RATA-RATA PEMBAYARAN
SELECT AVG(PAYAMOUNT) 
FROM transjakarta;
-- C. DISTRIBUSI PEMBAYARAN
SELECT payAmount, COUNT(*) AS paymentCount 
FROM transjakarta 
GROUP BY payAmount 
ORDER BY payAmount;
-- D. DISTRIBUSI KARTU PEMBAYARAN
SELECT PAYCARDBANK, COUNT(*) FROM transjakarta GROUP BY PAYCARDBANK;
-- E. Analisis pola frekuensi penggunaan transportasi menggunakan data tap-in dan tap-out.
SELECT payCardID, COUNT(*) AS frequency
FROM transjakarta
GROUP BY payCardID
ORDER BY frequency DESC;
-- ANALISIS PENGGUNAAN KARTU PEMBAYARAN
-- A. ANALISIS PENGGUNAAN KARTU PEMBAYARAN YANG PALING SERING DIGUNAKAN
SELECT PAYCARDBANK, COUNT(*) AS TOTAL_DIGUNAKAN 
FROM transjakarta 
GROUP BY PAYCARDBANK;
-- B. ANALISIS JENIS KELAMIN PENGGUNA DARI SETIAP KARTU PEMBAYARAN
SELECT PAYCARDBANK, PAYCARDSEX, COUNT(*) 
FROM transjakarta 
GROUP BY PAYCARDBANK, PAYCARDSEX;
-- C. ANALISIS UMUR PENGGUNA DARI SETIAP KARTU PEMBAYARAN
SELECT PAYCARDBANK, PAYCARDBIRTHDATE, COUNT(*) 
FROM transjakarta 
GROUP BY PAYCARDBANK, PAYCARDBIRTHDATE
ORDER BY PAYCARDBIRTHDATE ASC;
-- D. ANALISIS UMUR DAN JENIS KELAMIN SETIAP PENGGUNA KARTU PEMBAYARAN
SELECT PAYCARDBANK, PAYCARDSEX, PAYCARDBIRTHDATE, COUNT(*) 
FROM transjakarta 
GROUP BY PAYCARDBANK, PAYCARDSEX, PAYCARDBIRTHDATE
ORDER BY PAYCARDBANK, PAYCARDSEX, PAYCARDBIRTHDATE ASC;
-- E. ANALISIS KARTU PEMBAYARAN PADA TAPINSTOPSNAME
SELECT PAYCARDBANK, TAPINSTOPSNAME, COUNT(*) 
FROM transjakarta 
GROUP BY PAYCARDBANK, TAPINSTOPSNAME;
-- F. ANALISIS KARTU PEMBAYARAN PADA TAPOUTSTOPSNAME
SELECT PAYCARDBANK, TAPOUTSTOPSNAME, COUNT(*) 
FROM transjakarta 
GROUP BY PAYCARDBANK, TAPOUTSTOPSNAME;
-- G. ANALISIS KARTU PEMBAYARAN PADA TAPINSTOPSNAME DAN TAPOUTSTOPSNAME
SELECT PAYCARDBANK, TAPINSTOPSNAME, TAPOUTSTOPSNAME, COUNT(*) 
FROM transjakarta 
GROUP BY PAYCARDBANK, TAPINSTOPSNAME, TAPOUTSTOPSNAME
ORDER BY PAYCARDBANK, tapInStopsName, tapOutStopsName ASC;
-- H. ANALISIS RATA-RATA PENGGUNAAN DARI SETIAP KARTU PEMBAYARAN
SELECT payCardBank, AVG(payAmount) AS averagePayment
FROM transjakarta
GROUP BY payCardBank;
-- I. ANALISIS RATA-RATA PEMBAYARAN DARI SETIAP TRANSAKSI
SELECT PAYAMOUNT, AVG(PAYAMOUNT)
FROM transjakarta
GROUP BY PAYAMOUNT;
-- J. ANALSIS TREN PEMBAYARAN DARI WAKTU KE WAKTU
SELECT DATE_FORMAT(tapInTime, '%Y-%m-%d') AS DATE, COUNT(DISTINCT payCardID) AS uniqueUsers, PAYCARDBANK
FROM transjakarta
GROUP BY DATE, PAYCARDBANK
ORDER BY DATE;
-- ANALISIS RUTE DAN PEMBERHENTIAN
-- A. ANALISIS KORIDOR YANG PALING SERING DIGUNAKAN
SELECT CORRIDORID, COUNT(*) AS TOTAL_KORIDOR
FROM transjakarta 
GROUP BY CORRIDORID
ORDER BY CORRIDORID ASC;
-- B. ANALISIS PEMBERHENTIAN PALING SIBUK
SELECT TAPOUTSTOPSNAME, COUNT(*) AS TOTAL
FROM transjakarta
GROUP BY TAPOUTSTOPSNAME
ORDER BY TOTAL DESC;
-- C. WAKTU TEMPUH PERJALANAN RATA-RATA
SELECT tapInStopsName, tapOutStopsName, AVG(tapOutTime - tapInTime) AS averageTravelTime
FROM transjakarta
GROUP BY tapInStopsName, tapOutStopsName;
-- D. CORRIDOR DENGAN WAKTU TEMPUH PALING LAMA KE PALING CEPAT
SELECT CORRIDORID, SUM(TAPOUTTIME - TAPINTIME) AS WAKTU_TEMPUH
FROM transjakarta
GROUP BY CORRIDORID
ORDER BY WAKTU_TEMPUH DESC;
-- E. ANALISIS CORRIDOR DENGAN PEMBAYARAN PALING MAHAL KE PALING MURAH
SELECT CORRIDORID, PAYAMOUNT, COUNT(*)
FROM transjakarta 
GROUP BY CORRIDORID, PAYAMOUNT
ORDER BY PAYAMOUNT DESC;
-- F. ANALISIS GENERASI Z SEBAGAI PENGGUNA TRANSJAKARTA
SELECT PAYCARDBIRTHDATE, PAYCARDSEX, COUNT(*) 
FROM transjakarta
WHERE payCardBirthDate BETWEEN 1997 AND 2012
GROUP BY PAYCARDSEX, PAYCARDBIRTHDATE
ORDER BY PAYCARDBIRTHDATE ASC;
-- G. ANALISIS GENERASI MILLENIAL SEBAGAI PENGGUNA TRANSJAKARTA
SELECT PAYCARDBIRTHDATE, PAYCARDSEX, COUNT(*) 
FROM transjakarta
WHERE payCardBirthDate BETWEEN 1981 AND 1996
GROUP BY PAYCARDSEX, PAYCARDBIRTHDATE
ORDER BY PAYCARDBIRTHDATE ASC;
-- H. ANALISIS GENERASI X SEBAGAI PENGGUNA TRANSJAKARTA
SELECT PAYCARDBIRTHDATE, PAYCARDSEX, COUNT(*) 
FROM transjakarta
WHERE payCardBirthDate BETWEEN 1965 AND 1980
GROUP BY PAYCARDSEX, PAYCARDBIRTHDATE
ORDER BY PAYCARDBIRTHDATE ASC;
-- I. ANALISIS GENERASI BABYBOOMER SEBAGAI PENGGUNA TRANSJAKARTA
SELECT PAYCARDBIRTHDATE, PAYCARDSEX, COUNT(*) 
FROM transjakarta
WHERE payCardBirthDate BETWEEN 1946 AND 1964
GROUP BY PAYCARDSEX, PAYCARDBIRTHDATE
ORDER BY PAYCARDBIRTHDATE ASC;

