SELECT * FROM STUDENT;
-- ANALISIS JUMLAH TOTAL MAHASISWA 
SELECT COUNT(STUDENTNAME) AS TotalMahasiswa
FROM STUDENT;
-- DISTRIBUSI MAHASISWA BERDASARKAN PROGRAM STUDI
SELECT FIELDOFSTUDY, COUNT(*)
FROM STUDENT
GROUP BY FIELDOFSTUDY;
-- ANALISIS JUMLAH MAHASISWA YANG TERDAFTAR SETIAP TAHUNNYA
SELECT YEAROFADMISSION, COUNT(*) 
FROM STUDENT
GROUP BY YEAROFADMISSION
ORDER BY YEAROFADMISSION ASC;
-- ANALISIS TINGKAT KELULUSAN RATA-RATA
SELECT YearofAdmission, AVG(CAST(EXPECTEDGRADUATION AS FLOAT)) AS TingkatKelulusanRataRata
FROM STUDENT
GROUP BY YearofAdmission
ORDER BY YEAROFADMISSION;
-- DISTRIBUSI MAHASISWA BERDASARKAN SPESIALISASI
SELECT SPECIALIZATION, COUNT(*) 
FROM STUDENT 
GROUP BY SPECIALIZATION;
-- DISTRIBUSI MAHASISWA BERDASARKAN SEMESTER SAAT INI DAN SPESIALISASINYA
SELECT CURRENTSEMESTER, SPECIALIZATION, COUNT(*) 
FROM STUDENT
GROUP BY CURRENTSEMESTER, SPECIALIZATION
ORDER BY CURRENTSEMESTER ASC;
-- RATA-RATA UMUR MAHASISWA
SELECT AVG(DATEDIFF(year, DateofBirth, GETDATE())) AS RataRataUmur
FROM STUDENT
GROUP BY DATEOFBIRTH;
-- Perbandingan antara biaya pendidikan dan diskon pada biaya pendidikan per jurusan. 
SELECT FIELDOFSTUDY, AVG(Fees) AS RataRataBiayaPendidikan, AVG(DiscountOnFees) AS RataRataDiskon
FROM STUDENT
GROUP BY FIELDOFSTUDY;
-- ANALISIS MAHASISWA DENGAN BIAYA PENDIDIKAN TERTINGGI KE TERENDAH
SELECT STUDENTNAME, FEES
FROM STUDENT
ORDER BY FEES DESC;
-- ANALISIS JURUSAN DENGAN RATA-RATA BIAYA PENDIDIKAN TERTINGGI KE TERENDAH
SELECT FIELDOFSTUDY, AVG(FEES)
FROM STUDENT
GROUP BY FIELDOFSTUDY, FEES
ORDER BY FEES DESC;
-- ANALISIS MAHASISWA DENGAN DISKON PENDIDIKAN TERTINGGI KE TERENDAH
SELECT STUDENTNAME, DISCOUNTONFEES
FROM STUDENT 
GROUP BY STUDENTNAME, DISCOUNTONFEES
ORDER BY DISCOUNTONFEES DESC;
-- ANALISIS PEMBAYARAN MAHASISWA SETELAH DIPOTONG DISKON
SELECT STUDENTNAME, SUM(FEES - DISCOUNTONFEES) AS PEMBAYARANAKHIR 
FROM STUDENT
GROUP BY STUDENTNAME
ORDER BY PEMBAYARANAKHIR DESC;
-- ANALSISI JUMLAH MAHASISWA DENGAN PEMBAYARAN = GRATIS
SELECT STUDENTNAME, FEES 
FROM STUDENT
WHERE FEES = 0;
-- JUMLAH MAHASISWA YANG DITERIMA PER JURUSAN PER TAHUNNYA
SELECT FIELDOFSTUDY, YEAROFADMISSION, COUNT(*)
FROM STUDENT 
GROUP BY FIELDOFSTUDY, YEAROFADMISSION
ORDER BY YEAROFADMISSION ASC;
-- JUMLAH MAHASISWA YANG DITERIMA PER SPESIALISASINYA PER TAHUNNYA
SELECT SPECIALIZATION, YEAROFADMISSION, COUNT(*)
FROM STUDENT 
GROUP BY SPECIALIZATION, YEAROFADMISSION
ORDER BY YEAROFADMISSION ASC;
-- RATA-RATA MAHASISWA YANG DITERIMA PERTAHUNNYA
SELECT YearofAdmission, AVG(StudentCount) AS RataRataMahasiswaDiterima
FROM (
    SELECT YearofAdmission, COUNT(*) AS StudentCount
    FROM STUDENT
    GROUP BY YearofAdmission
) AS SubQuery
GROUP BY YearofAdmission
ORDER BY YEAROFADMISSION ASC;
-- ANALISIS MAHASISWA DENGAN BIAYA PENDIDIKAN DIBAWAH 100000
SELECT STUDENTNAME, FEES, DISCOUNTONFEES, SUM(FEES - DISCOUNTONFEES) AS TOTAL
FROM STUDENT
WHERE FEES <=100000
GROUP BY STUDENTNAME, FEES, DISCOUNTONFEES
ORDER BY FEES DESC;
-- ANALISIS MAHASISWA DENGAN BIAYA PENDIDIKAN DIATAS 100000
SELECT STUDENTNAME, FEES, DISCOUNTONFEES, SUM(FEES - DISCOUNTONFEES) AS TOTAL
FROM STUDENT
WHERE FEES >=100000
GROUP BY STUDENTNAME, FEES, DISCOUNTONFEES
ORDER BY FEES DESC;
-- ANALSIS MAHASIWA DENGAN PEMBAYARAN TERTINGGI TAPI DISKON TERENDAH
SELECT StudentID, StudentName, Fees, DiscountOnFees
FROM Student
WHERE (Fees - DiscountOnFees) = 
(SELECT MAX(Fees - DiscountOnFees) FROM Student);
-- ANALISIS MAHASISWA DENGAN PEMBAYARAN TERENDAH TAPI DISKON TERTINGGI
SELECT StudentID, StudentName, Fees, DiscountOnFees
FROM Student
WHERE (Fees - DiscountOnFees) = (SELECT MIN(Fees - DiscountOnFees) FROM Student)


