SELECT * FROM SALARIES;
-- 1. ANALISIS DATA NULL
SELECT * 
FROM SALARIES
WHERE WORK_YEAR IS NULL;

-- 2. ANALISIS JOB TITLE
SELECT  DISTINCT JOB_TITLE
FROM SALARIES
ORDER BY JOB_TITLE ASC;

-- 3. ANALISIS PEKERJAAN YANG BERKAITAN DENGAN DATA ANALYST
SELECT DISTINCT JOB_TITLE 
FROM SALARIES
WHERE JOB_TITLE LIKE'%DATA ANALYST%'
ORDER BY JOB_TITLE ASC;

-- 4. GAJI RATA-RATA YANG BERKAITAN DENGAN DATA ANALYST
SELECT AVG(SALARY_IN_USD)
FROM SALARIES
WHERE JOB_TITLE LIKE'%DATA ANALYST%';

-- 5. GAJI RATA-RATA SELURUH PEKERJAAN DATA
SELECT AVG(SALARY_IN_USD)
FROM SALARIES;

-- 6. GAJI RATA- RATA YANG BERKAITAN DENGAN DATA ANALYST DALAM PERBULANNYA
SELECT AVG(SALARY_IN_USD)/12
FROM SALARIES
WHERE JOB_TITLE LIKE'%DATA ANALYST%';

-- 7. GAJI RATA-RATA SELURUH PEKERJAAN DATA DALAM PERBULANNYA
SELECT AVG(SALARY_IN_USD)/12
FROM SALARIES;

-- 8. GAJI RATA-RATA SELURUH PEKERJAAN JIKA DI CONVERT KE DALAM RUPIAH DAN PERBULANNYA
SELECT AVG(SALARY_IN_USD) * 15161.70 AS GAJI_PERTAHUN, (AVG(SALARY_IN_USD) * 15161.70)/12 AS GAJI_PERBULAN
FROM SALARIES;

-- 9. GAJI RATA-RATA BERDASARKAN EXPERIENCE LEVEL
SELECT EXPERIENCE_LEVEL, AVG(SALARY_IN_USD) 
FROM SALARIES
GROUP BY EXPERIENCE_LEVEL;

-- 10. GAJI RATA-RATA BERDASARKAN EXPERIENCE LEVEL DALAM RUPIAH
SELECT EXPERIENCE_LEVEL, 
AVG(SALARY_IN_USD)*15161 AS GAJI_PERTAHUN, 
(AVG(SALARY_IN_USD)*15161)/12 AS GAJI_PERBULAN
FROM SALARIES
GROUP BY EXPERIENCE_LEVEL;

-- 11. GAJI RATA-RATA BERDASARKAN EMPLOYMENT TYPE
SELECT EMPLOYMENT_TYPE, AVG(SALARY_IN_USD) 
FROM SALARIES 
GROUP BY EMPLOYMENT_TYPE;

-- 12. GAJI RATA-RATA BERDASARKAN EMPLOYMENT TYPE DALAM RUPIAH DAN PERBULAN
SELECT EMPLOYMENT_TYPE, 
AVG(SALARY_IN_USD)*15161 AS GAJI_PERTAHUN, 
(AVG(SALARY_IN_USD)*15161)/12 AS GAJI_PERBULAN
FROM SALARIES
GROUP BY EMPLOYMENT_TYPE;

-- 13. GAJI RATA-RATA BERDASARKAN EXPERIENCE LEVEL DAN EMPLOYMENT TYPE
SELECT EXPERIENCE_LEVEL, EMPLOYMENT_TYPE, AVG(SALARY_IN_USD) 
FROM SALARIES 
GROUP BY EXPERIENCE_LEVEL, EMPLOYMENT_TYPE
ORDER BY EXPERIENCE_LEVEL;

-- 14. GAJI RATA-RATA BERDASARKAN EXPERIENCE LEVEL DAN EMPLOYMENT TYPE DALAM RUPIAH DAN PERBULANNYA
SELECT EXPERIENCE_LEVEL, EMPLOYMENT_TYPE, 
AVG(SALARY_IN_USD)*15161 AS GAJI_PERTAHUN, 
(AVG(SALARY_IN_USD)*15161)/12 AS GAJI_PERBULAN
FROM SALARIES 
GROUP BY EXPERIENCE_LEVEL, EMPLOYMENT_TYPE
ORDER BY EXPERIENCE_LEVEL;

-- 15. GAJI RATA-RATA BERDASARKAN JOB TITLE
SELECT DISTINCT JOB_TITLE, AVG(SALARY_IN_USD)
FROM SALARIES
GROUP BY JOB_TITLE
ORDER BY JOB_TITLE;

-- 16. GAJI RATA-RATA BERDASARKAN JOB TITLE DALAM RUPIAH DAN PERBULAN
SELECT DISTINCT JOB_TITLE, 
AVG(SALARY_IN_USD)*15161 AS GAJI_PERTAHUN, 
(AVG(SALARY_IN_USD)*15161)/12 AS GAJI_PERBULAN
FROM SALARIES
GROUP BY JOB_TITLE
ORDER BY JOB_TITLE;

-- 17. GAJI RATA-RATA BERDASARKAN JOB TITLE DAN EXPERIENCE LEVEL
SELECT DISTINCT JOB_TITLE, EXPERIENCE_LEVEL, AVG(SALARY_IN_USD)
FROM SALARIES
GROUP BY JOB_TITLE, EXPERIENCE_LEVEL
ORDER BY JOB_TITLE;

-- 18. GAJI RATA-RATA BERDASARKAN JOB TITLE DAN EXPERIENCE LEVEL DALAM RUPIAH DAN PERBULANNYA
SELECT DISTINCT JOB_TITLE, EXPERIENCE_LEVEL, 
AVG(SALARY_IN_USD)*15161 AS GAJI_PERTAHUN, 
(AVG(SALARY_IN_USD)*15161)/12 AS GAJI_PERBULAN
FROM SALARIES
GROUP BY JOB_TITLE, EXPERIENCE_LEVEL
ORDER BY JOB_TITLE;

-- 19. GAJI RATA-RATA BERDASARKAN JOB TITLE DAN EMPLOYMENT TYPE
SELECT DISTINCT JOB_TITLE, EMPLOYMENT_TYPE, AVG(SALARY_IN_USD)
FROM SALARIES
GROUP BY JOB_TITLE, EMPLOYMENT_TYPE
ORDER BY JOB_TITLE;

-- 20. GAJI RATA-RATA BERDASARKAN JOB TITLE DAN EMPLOYMENT TYPE DALAM RUPIAH DAN PERBULAN
SELECT DISTINCT JOB_TITLE, EMPLOYMENT_TYPE, 
AVG(SALARY_IN_USD)*15161 AS GAJI_PERTAHUN, 
(AVG(SALARY_IN_USD)*15161)/12 AS GAJI_PERBULAN
FROM SALARIES
GROUP BY JOB_TITLE, EMPLOYMENT_TYPE
ORDER BY JOB_TITLE;

-- 21. GAJI RATA-RATA JT, ET, EL
SELECT DISTINCT JOB_TITLE, EXPERIENCE_LEVEL, EMPLOYMENT_TYPE, AVG(SALARY_IN_USD)
FROM SALARIES
GROUP BY JOB_TITLE, EXPERIENCE_LEVEL, EMPLOYMENT_TYPE
ORDER BY JOB_TITLE;

-- 22. GAJI RATA RATA JT, ET, EL DALAM RUPIAH DAN PERBULAN
SELECT DISTINCT JOB_TITLE, EXPERIENCE_LEVEL, EMPLOYMENT_TYPE, 
AVG(SALARY_IN_USD)*15161 AS GAJI_PERTAHUN, 
(AVG(SALARY_IN_USD)*15161)/12 AS GAJI_PERBULAN
FROM SALARIES
GROUP BY JOB_TITLE, EXPERIENCE_LEVEL, EMPLOYMENT_TYPE
ORDER BY JOB_TITLE;

-- 23. GAJI RATA RATA BERDASARKAN EMPLOYEE RESIDENCE
SELECT EMPLOYEE_RESIDENCE, AVG(SALARY_IN_USD)
FROM SALARIES 
GROUP BY EMPLOYEE_RESIDENCE
ORDER BY EMPLOYEE_RESIDENCE;

-- 24. GAJI RATA RATA BERDASARKAN EMPLOYEE RESIDENCE DALAM RUPIAH DAN PERBULAN
SELECT EMPLOYEE_RESIDENCE, 
AVG(SALARY_IN_USD)*15161 AS GAJI_PERTAHUN, 
(AVG(SALARY_IN_USD)*15161)/12 AS GAJI_PERBULAN
FROM SALARIES 
GROUP BY EMPLOYEE_RESIDENCE
ORDER BY EMPLOYEE_RESIDENCE;

-- 25. GAJI RATA RATA BERDASARKAN JOB TITLE DAN EMPLOYEE RESIDENCE
SELECT DISTINCT JOB_TITLE, EMPLOYEE_RESIDENCE, AVG(SALARY_IN_USD)
FROM SALARIES
GROUP BY JOB_TITLE, EMPLOYEE_RESIDENCE
ORDER BY EMPLOYEE_RESIDENCE;

-- 26. GAJI RATA RATA BERDASARKAN JOB TITLE DAN EMPLOYEE RESIDENCE DALAM RUPIAH DAN PERBULAN
SELECT DISTINCT JOB_TITLE, EMPLOYEE_RESIDENCE, 
AVG(SALARY_IN_USD)*15161 AS GAJI_PERTAHUN, 
(AVG(SALARY_IN_USD)*15161)/12 AS GAJI_PERBULAN
FROM SALARIES
GROUP BY JOB_TITLE, EMPLOYEE_RESIDENCE
ORDER BY EMPLOYEE_RESIDENCE;

-- 27. GAJI RATA-RATA BERDASARKAN JOB TITLE, EMPLOYEE RESIDENCE DAN EMPLOYMENT TYPE
SELECT DISTINCT JOB_TITLE, EMPLOYEE_RESIDENCE, EMPLOYMENT_TYPE, AVG(SALARY_IN_USD)
FROM SALARIES
GROUP BY JOB_TITLE, EMPLOYEE_RESIDENCE, EMPLOYMENT_TYPE
ORDER BY EMPLOYEE_RESIDENCE;

-- 28. GAJI RATA-RATA BERDASARKAN JOB TITLE, EMPLOYEE RESIDENCE DAN EMPLOYMENT TYPE
SELECT DISTINCT JOB_TITLE, EMPLOYEE_RESIDENCE, EMPLOYMENT_TYPE, 
AVG(SALARY_IN_USD)*15161 AS GAJI_PERTAHUN, 
(AVG(SALARY_IN_USD)*15161)/12 AS GAJI_PERBULAN
FROM SALARIES
GROUP BY JOB_TITLE, EMPLOYEE_RESIDENCE, EMPLOYMENT_TYPE
ORDER BY EMPLOYEE_RESIDENCE;

-- 29. GAJI RATA RATA BERDASARKAN JOB TITLE, EMPLOYEE RESIDENCE DAN EXPERIENCE LEVEL
SELECT DISTINCT JOB_TITLE, EMPLOYEE_RESIDENCE, EXPERIENCE_LEVEL, AVG(SALARY_IN_USD)
FROM SALARIES
GROUP BY JOB_TITLE, EMPLOYEE_RESIDENCE, EXPERIENCE_LEVEL
ORDER BY EMPLOYEE_RESIDENCE;

-- 30. GAJI RATA RATA BERDASARKAN JOB TITLE, EMPLOYEE RESIDENCE DAN EXPERIENCE LEVEL DALAM RUPIAH DAN PERBULAN
SELECT DISTINCT JOB_TITLE, EMPLOYEE_RESIDENCE, EXPERIENCE_LEVEL, 
AVG(SALARY_IN_USD)*15161 AS GAJI_PERTAHUN, 
(AVG(SALARY_IN_USD)*15161)/12 AS GAJI_PERBULAN
FROM SALARIES
GROUP BY JOB_TITLE, EMPLOYEE_RESIDENCE, EXPERIENCE_LEVEL
ORDER BY EMPLOYEE_RESIDENCE;

-- 31. GAJI RATA RATA BERDASARKAN JOB TITLE, EMPLOYEE RESIDENCE, EMPLOYMENT TYPE DAN EXPERIENCE LEVEL
SELECT DISTINCT JOB_TITLE, EMPLOYEE_RESIDENCE, EMPLOYMENT_TYPE, EXPERIENCE_LEVEL, AVG(SALARY_IN_USD)
FROM SALARIES
GROUP BY JOB_TITLE, EMPLOYEE_RESIDENCE, EMPLOYMENT_TYPE, EXPERIENCE_LEVEL
ORDER BY EMPLOYEE_RESIDENCE;

-- 32. GAJI RATA RATA BERDASARKAN JOB TITLE, EMPLOYEE RESIDENCE, EMPLOYMENT TYPE DAN EXPERIENCE LEVEL DALAM RUPIAH DAN PERBULAN
SELECT DISTINCT JOB_TITLE, EMPLOYEE_RESIDENCE, EMPLOYMENT_TYPE, EXPERIENCE_LEVEL, 
AVG(SALARY_IN_USD)*15161 AS GAJI_PERTAHUN, 
(AVG(SALARY_IN_USD)*15161)/12 AS GAJI_PERBULAN
FROM SALARIES
GROUP BY JOB_TITLE, EMPLOYEE_RESIDENCE, EMPLOYMENT_TYPE, EXPERIENCE_LEVEL
ORDER BY EMPLOYEE_RESIDENCE;

-- 33. GAJI RATA RATA BERDSARKAN REMOTE RATIO
SELECT REMOTE_RATIO, AVG(SALARY_IN_USD)
FROM SALARIES
GROUP BY REMOTE_RATIO;

-- 34. GAJI RATA RATA BERDASARKAN COMPANY SIZE
SELECT COMPANY_SIZE, AVG(SALARY_IN_USD)
FROM SALARIES
GROUP BY COMPANY_SIZE;

-- 35. GAJI RATA RATA BERDASARKAN COMPANY SIZE DAN REMOTE RATIO
SELECT COMPANY_SIZE, REMOTE_RATIO, AVG(SALARY_IN_USD)
FROM SALARIES
GROUP BY COMPANY_SIZE, REMOTE_RATIO
ORDER BY REMOTE_RATIO;

-- 36. GAJI RATA RATA BERDSARKAN COMPANY SIZE DAN REMOTE RATIO DALAM RUPIAH DAN PERBULAN
SELECT COMPANY_SIZE, REMOTE_RATIO, 
AVG(SALARY_IN_USD)*15161 AS GAJI_PERTAHUN, 
(AVG(SALARY_IN_USD)*15161)/12 AS GAJI_PERBULAN
FROM SALARIES
GROUP BY COMPANY_SIZE, REMOTE_RATIO
ORDER BY REMOTE_RATIO;

-- 37. GAJI RATA RATA BERDASARKAN EXPERIENCE LEVEL DAN REMOTE RATIO
SELECT EXPERIENCE_LEVEL, REMOTE_RATIO, AVG(SALARY_IN_USD)
FROM SALARIES
GROUP BY EXPERIENCE_LEVEL, REMOTE_RATIO
ORDER BY REMOTE_RATIO;

-- 38. GAJI RATA RATA BERDASARKAN EXPERIENCE LEVEL DAN REMOTE RATIO
SELECT EXPERIENCE_LEVEL, REMOTE_RATIO, 
AVG(SALARY_IN_USD)*15161 AS GAJI_PERTAHUN, 
(AVG(SALARY_IN_USD)*15161)/12 AS GAJI_PERBULAN
FROM SALARIES
GROUP BY EXPERIENCE_LEVEL, REMOTE_RATIO
ORDER BY REMOTE_RATIO;

-- 39. GAJI RATA RATA BERDASARKAN EXPERIENCE LEVEL DAN COMPANY SIZE
SELECT EXPERIENCE_LEVEL, COMPANY_SIZE, AVG(SALARY_IN_USD)
FROM SALARIES
GROUP BY EXPERIENCE_LEVEL, COMPANY_SIZE
ORDER BY COMPANY_SIZE;

-- 40. GAJI RATA RATA BERDASARKAN EXPERIENCE LEVEL DAN COMPANY SIZE DALAM RUPIAH DAN PERBULAN
SELECT EXPERIENCE_LEVEL, COMPANY_SIZE, AVG(SALARY_IN_USD)*15161 AS GAJI_PERTAHUN, 
(AVG(SALARY_IN_USD)*15161)/12 AS GAJI_PERBULAN
FROM SALARIES
GROUP BY EXPERIENCE_LEVEL, COMPANY_SIZE
ORDER BY COMPANY_SIZE;

-- 41. PEKERJAAN DENGAN GAJI TERTINGGI
SELECT JOB_TITLE, SALARY_IN_USD
FROM SALARIES
GROUP BY JOB_TITLE, SALARY_IN_USD
ORDER BY SALARY_IN_USD DESC;

-- 42. PEKERJAAN DENGAN GAJI TERTINGGI BERDASARKAN NEGARA PEKERJA
SELECT JOB_TITLE, EMPLOYEE_RESIDENCE, SALARY_IN_USD
FROM SALARIES
GROUP BY JOB_TITLE, EMPLOYEE_RESIDENCE, SALARY_IN_USD
ORDER BY SALARY_IN_USD DESC;

-- 43. PEKERJAAN DENGAN GAJI TERTINGGI BERDASARKAN REMOTE RATIO
SELECT JOB_TITLE, REMOTE_RATIO, SALARY_IN_USD
FROM SALARIES
GROUP BY JOB_TITLE, REMOTE_RATIO, SALARY_IN_USD
ORDER BY SALARY_IN_USD DESC;

-- 44. PEKERJAAN DENGAN GAJI TERTINGGI BERDASARKAN REMOTE RATIO DAN NEGARA PEKERJA
SELECT JOB_TITLE, REMOTE_RATIO, EMPLOYEE_RESIDENCE, SALARY_IN_USD
FROM SALARIES
GROUP BY JOB_TITLE, REMOTE_RATIO, EMPLOYEE_RESIDENCE, SALARY_IN_USD
ORDER BY SALARY_IN_USD DESC;

-- 45. PEKERJAAN DENGAN GAJI TERTINGGI BERDASARKAN LOKASI PERUSAHAAN DAN UKURAN PERUSAHAAN
SELECT COMPANY_LOCATION, COMPANY_SIZE, SALARY_IN_USD
FROM SALARIES
GROUP BY COMPANY_LOCATION, COMPANY_SIZE, SALARY_IN_USD
ORDER BY SALARY_IN_USD DESC;

-- 46. PEKERJAAN DENGAN GAJI TERTINGGI BERDASARKAN LOKASI PERUSAHAAN DAN REMOTE RATIO
SELECT COMPANY_LOCATION, REMOTE_RATIO, SALARY_IN_USD
FROM SALARIES
GROUP BY COMPANY_LOCATION, REMOTE_RATIO, SALARY_IN_USD
ORDER BY SALARY_IN_USD DESC;

-- 47. PEKERJAAN DENGAN GAJI TERTINGGI BERDASARKAN LOKASI PERUSAHAAN DAN EXPERIENCE LEVEL
SELECT COMPANY_LOCATION, EXPERIENCE_LEVEL, SALARY_IN_USD
FROM SALARIES
GROUP BY COMPANY_LOCATION, EXPERIENCE_LEVEL, SALARY_IN_USD
ORDER BY EXPERIENCE_LEVEL, SALARY_IN_USD DESC;

-- 48. PEKERJAAN DENGAN GAJI TERTINGGI BERDASARKAN EXPERIENCE LEVEL DAN LOKASI PERUSAHAAN TAPI FULL REMOTE
SELECT COMPANY_LOCATION, EXPERIENCE_LEVEL, REMOTE_RATIO, SALARY_IN_USD
FROM SALARIES
WHERE REMOTE_RATIO = 100
GROUP BY COMPANY_LOCATION, EXPERIENCE_LEVEL, SALARY_IN_USD
ORDER BY EXPERIENCE_LEVEL, SALARY_IN_USD DESC;

-- 49. PEKERJAAN DENGAN GAJI TERTINGGI TAPI BISA FULL REMOTE
SELECT DISTINCT JOB_TITLE, REMOTE_RATIO, SALARY_IN_USD
FROM SALARIES
WHERE REMOTE_RATIO = 100
GROUP BY JOB_TITLE, REMOTE_RATIO, SALARY_IN_USD
ORDER BY SALARY_IN_USD DESC;

-- 50. PEKERJAAN DENGAN GAJI TERTINGGI TAPI BISA FULL REMOTE DALAM RUPIAH DAN PERBULAN
SELECT DISTINCT JOB_TITLE, REMOTE_RATIO,
(SALARY_IN_USD)*15161 AS GAJI_PERTAHUN, 
((SALARY_IN_USD)*15161)/12 AS GAJI_PERBULAN
FROM SALARIES
WHERE REMOTE_RATIO = 100
GROUP BY JOB_TITLE, REMOTE_RATIO, SALARY_IN_USD
ORDER BY GAJI_PERTAHUN DESC;
