SELECT * FROM PURCHASE;
-- ANALISIS PEMBELIAN BERDASARKAN TANGGAL
SELECT ORDER_DATE, COUNT(ORDER_DATE) AS JUMLAH FROM PURCHASE GROUP BY ORDER_DATE;
-- ANALISIS PEMBELIAN BERDASARKAN ORGANISASI
SELECT ORGANISATION_NAME, COUNT(ORGANISATION_NAME) FROM PURCHASE GROUP BY ORGANISATION_NAME;
-- ANALISIS PEMBELIAN BERDASARKAN SUPPLIER
SELECT SUPPLIER_NAME, COUNT(SUPPLIER_NAME) AS JUMLAH FROM PURCHASE GROUP BY SUPPLIER_NAME;
-- ANALISIS PEMBELIAN BERDASARKAN LAYANAN
SELECT SERVICE, COUNT(SERVICE) AS JUMLAH FROM PURCHASE GROUP BY SERVICE;
-- ANALISIS PEMBELIAN BERDASARKAN AKUN
SELECT ACCOUNT_NAME, COUNT(ACCOUNT_NAME) AS JUMLAH FROM PURCHASE GROUP BY ACCOUNT_NAME;
-- ANALISIS HUBUNGAN ANTARA TOTAL NILAI PEMBELIAN DAN TANGGAL
SELECT TOTAL_VALUE, ORDER_DATE FROM PURCHASE;
-- ANALISIS TOTAL_VALUE DARI SETIAP SERVICE
SELECT SERVICE, SUM(TOTAL_VALUE) AS TOTAL_SERVICE_VALUE FROM PURCHASE GROUP BY SERVICE;
-- analisis purchase_order berdasarkan service
SELECT SERVICE, COUNT(DISTINCT(PURCHASE_ORDER)) FROM PURCHASE GROUP BY SERVICE;
-- analisis supplier_name berdasarkan account_name
SELECT DISTINCT(ACCOUNT_NAME), SUPPLIER_NAME, COUNT(*) AS TOTAL_ACCOUNT FROM PURCHASE GROUP BY SUPPLIER_NAME, ACCOUNT_NAME 
ORDER BY TOTAL_ACCOUNT DESC;
-- ANALISIS JUMLAH SETIAP ACCOUNT_NAME YANG LEBIH DARI 10
SELECT ACCOUNT_NAME, COUNT(*) AS TOTAL_COUNT 
FROM PURCHASE 
GROUP BY ACCOUNT_NAME HAVING COUNT(*) >10;
-- ANALISIS JUMLAH SETIAP SUPPLIER_NAME BETWEEN 10 AND 25
SELECT SUPPLIER_NAME, COUNT(*) AS TOTAL_COUNT 
FROM PURCHASE 
GROUP BY SUPPLIER_NAME
HAVING COUNT(*) BETWEEN 10 AND 25 ORDER BY TOTAL_COUNT DESC;
